# Generated by Django 6.1.1 on 2026-10-04 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('owner', 'Owner'), ('worker', 'Worker')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account_entity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Entity',
                'verbose_name_plural': 'Account Entities',
                'constraints': [models.UniqueConstraint(condition=models.Q(('entity_type', 'owner'), ('is_active', True)), fields=('entity_type',), name='accounts_single_owner_entity')],
            },
        ),
    ]
