# Generated by Django 6.1.1
import django.db.models.deletion
from django.contrib.auth import models as auth_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_accountentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=auth_models.User,
            ),
        ),
    ]
