# Generated by Django 6.1.1 on 2026-09-26 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_advertiserprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='accountentity',
            constraint=models.UniqueConstraint(condition=models.Q(('entity_type', 'owner')), fields=('entity_type',), name='accounts_single_owner_entity'),
        ),
    ]
