# Generated by Django 6.1.1 on 2026-10-07

from django.db import migrations, models
from django.db.models import F


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_protect_worker_profile_user"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="worker_profile_balance_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_balance__gte", 0)),
                name="worker_profile_reserved_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_earned__gte", 0)),
                name="worker_profile_total_earned_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="workerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserved_balance__lte", F("balance")),
                ),
                name="worker_profile_reserved_lte_balance",
            ),
        ),
    ]
