# Generated by Django 6.1.1 on 2026-09-26 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accountentity_accounts_single_owner_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerIdentityBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('mobile_verified_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_entity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_identity_binding', to='accounts.accountentity')),
                ('telegram_identity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_identity_binding', to='accounts.telegramidentity')),
            ],
        ),
    ]
