# Generated by Django 6.1.1 on 2026-09-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_owneremailverificationchallenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerSocialIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("facebook", "Facebook"), ("instagram", "Instagram")], max_length=32)),
                ("provider_user_id", models.CharField(max_length=255)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owner_social_identities", to="accounts.accountentity")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("provider", "provider_user_id"), name="accounts_unique_owner_social_identity"),
                ],
            },
        ),
    ]
