# Generated by Django 6.1.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_ownersocialoauthstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerNominee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("super_nominee", "Super Nominee"), ("nominee", "Nominee")], default="nominee", max_length=32)),
                ("succession_order", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("appointed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("nominee_user", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="owner_nomination", to=settings.AUTH_USER_MODEL)),
                ("owner_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owner_nominees", to="accounts.accountentity")),
            ],
            options={
                "ordering": ("succession_order", "appointed_at"),
            },
        ),
        migrations.AddConstraint(
            model_name="ownernominee",
            constraint=models.UniqueConstraint(fields=("owner_entity", "succession_order"), name="accounts_unique_nominee_succession_order"),
        ),
        migrations.AddConstraint(
            model_name="ownernominee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "super_nominee"), ("is_active", True)),
                fields=("owner_entity",),
                name="accounts_single_active_super_nominee",
            ),
        ),
    ]
