# Generated by Django 6.1.1 on 2026-10-04 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_harden_ownertrusteddevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ownernominee',
            name='accounts_single_active_super_nominee',
        ),
        migrations.RenameIndex(
            model_name='ownertrusteddevice',
            new_name='acct_owner_dev_status_idx',
            old_name='accounts_owner_device_status_idx',
        ),
        migrations.AlterField(
            model_name='ownersocialoauthstate',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='ownernominee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'super_nominee')), fields=('owner_entity',), name='accounts_single_active_super_nominee'),
        ),
    ]
