# Generated by Django 6.1.1 on 2026-10-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_ownernominee_accounts_single_active_super_nominee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerSessionBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("binding_token_hash", models.CharField(max_length=64, unique=True)),
                ("session_key_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_session_bindings",
                        to="accounts.accountentity",
                    ),
                ),
                (
                    "trusted_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_bindings",
                        to="accounts.ownertrusteddevice",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("owner_entity", "session_key_hash"),
                        name="acct_owner_sess_active_uniq",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("owner_entity", "revoked_at"),
                        name="acct_owner_sess_rev_idx",
                    ),
                ],
            },
        ),
    ]
