# Generated by Django 6.1.1 on 2026-10-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_ownersessionbinding"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountentity",
            name="webauthn_user_handle",
            field=models.BinaryField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="OwnerWebAuthnCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credential_id", models.BinaryField(max_length=1024, unique=True)),
                ("public_key", models.BinaryField(max_length=4096)),
                ("user_handle", models.BinaryField(max_length=64)),
                ("sign_count", models.PositiveBigIntegerField(default=0)),
                ("aaguid", models.CharField(blank=True, max_length=36)),
                ("transports", models.JSONField(blank=True, default=list)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("backup_eligible", models.BooleanField(default=False)),
                ("backed_up", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webauthn_credentials",
                        to="accounts.accountentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=("owner_entity", "revoked_at"),
                        name="acct_owner_webauthn_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerWebAuthnChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key_hash", models.CharField(max_length=64)),
                (
                    "ceremony",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("authentication", "Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                ("challenge_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webauthn_challenges",
                        to="accounts.accountentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=("owner_entity", "ceremony", "created_at"),
                        name="acct_owner_webauthn_chal_idx",
                    ),
                ],
            },
        ),
    ]
