# Generated by Django 6.1.1 on 2026-10-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_ownerwebauthn"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownersessionbinding",
            name="webauthn_credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session_bindings",
                to="accounts.ownerwebauthncredential",
            ),
        ),
        migrations.AlterField(
            model_name="ownersessionbinding",
            name="trusted_device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="session_bindings",
                to="accounts.ownertrusteddevice",
            ),
        ),
    ]
