# Generated by Django 6.1.1 on 2026-10-04

from datetime import timedelta

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_owner_binding_expiry(apps, schema_editor):
    OwnerSessionBinding = apps.get_model("accounts", "OwnerSessionBinding")
    expiry = timezone.now() + timedelta(
        seconds=settings.OWNER_SESSION_BINDING_TTL_SECONDS
    )
    OwnerSessionBinding.objects.filter(expires_at__isnull=True).update(
        expires_at=expiry
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_owner_session_binding_webauthn"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownersessionbinding",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(
            backfill_owner_binding_expiry,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="ownersessionbinding",
            name="expires_at",
            field=models.DateTimeField(),
        ),
    ]
