# Generated by Django 6.1.1 on 2026-09-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-requested_at'], 'permissions': [('approve_withdrawal', 'Can approve withdrawals'), ('reject_withdrawal', 'Can reject withdrawals'), ('mark_withdrawal_paid', 'Can mark withdrawals as paid')]},
        ),
    ]
