# Generated by Django 6.1.1 on 2026-10-05
import re

import django.db.models.deletion
from django.db import migrations, models


WITHDRAWAL_DESCRIPTION_RE = re.compile(r"^Withdrawal #(\d+)$")


def backfill_withdrawal_operation_identity(apps, schema_editor):
    WalletTransaction = apps.get_model("wallet", "WalletTransaction")
    WithdrawalRequest = apps.get_model("wallet", "WithdrawalRequest")

    withdrawal_transactions = (
        WalletTransaction.objects
        .filter(transaction_type="withdrawal")
        .order_by("id")
    )

    for transaction in withdrawal_transactions.iterator():
        match = WITHDRAWAL_DESCRIPTION_RE.fullmatch(transaction.description or "")
        if not match:
            raise RuntimeError(
                f"Cannot safely bind withdrawal ledger transaction {transaction.pk}: "
                "description does not contain an exact Withdrawal #<id> reference."
            )

        withdrawal_id = int(match.group(1))
        try:
            withdrawal = WithdrawalRequest.objects.get(pk=withdrawal_id)
        except WithdrawalRequest.DoesNotExist as exc:
            raise RuntimeError(
                f"Cannot safely bind withdrawal ledger transaction {transaction.pk}: "
                f"withdrawal {withdrawal_id} does not exist."
            ) from exc

        if transaction.user_id != withdrawal.user_id:
            raise RuntimeError(
                f"Cannot safely bind withdrawal ledger transaction {transaction.pk}: "
                "ledger user does not match withdrawal user."
            )

        if transaction.amount != withdrawal.amount:
            raise RuntimeError(
                f"Cannot safely bind withdrawal ledger transaction {transaction.pk}: "
                "ledger amount does not match withdrawal amount."
            )

        if transaction.task_claim_id is not None or transaction.promotion_claim_id is not None:
            raise RuntimeError(
                f"Cannot safely bind withdrawal ledger transaction {transaction.pk}: "
                "transaction is already linked to another operation type."
            )

        existing = (
            WalletTransaction.objects
            .filter(withdrawal_id=withdrawal_id)
            .exclude(pk=transaction.pk)
            .values_list("pk", flat=True)
            .first()
        )
        if existing is not None:
            raise RuntimeError(
                f"Cannot safely bind withdrawal {withdrawal_id}: "
                f"multiple withdrawal ledger transactions exist ({existing}, {transaction.pk})."
            )

        transaction.withdrawal_id = withdrawal_id
        transaction.save(update_fields=["withdrawal"])


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_withdrawalrequest_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="withdrawal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transaction",
                to="wallet.withdrawalrequest",
            ),
        ),
        migrations.RunPython(
            backfill_withdrawal_operation_identity,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
