# Generated by Django 6.1.1 on 2026-10-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0005_wallettransaction_withdrawal_identity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("task_claim__isnull", True))
                    | models.Q(("transaction_type", "earning"))
                ),
                name="wallet_tx_task_identity_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("promotion_claim__isnull", True))
                    | models.Q(("transaction_type", "earning"))
                ),
                name="wallet_tx_promotion_identity_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("withdrawal__isnull", True))
                    | models.Q(("transaction_type", "withdrawal"))
                ),
                name="wallet_tx_withdrawal_identity_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallettransaction",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("task_claim__isnull", True))
                    | models.Q(("promotion_claim__isnull", True))
                    | models.Q(("withdrawal__isnull", True))
                ),
                name="wallet_tx_single_operation_identity",
            ),
        ),
    ]
