# Generated by Django 6.1.1
import django.db.models.deletion
from django.contrib.auth import models as auth_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_wallettransaction_operation_identity_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet_transactions",
                to=auth_models.User,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawal_requests",
                to=auth_models.User,
            ),
        ),
    ]
