# Generated by Django 6.1.1 on 2026-10-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0006_wallettransaction_operation_identity_constraints"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="withdrawalrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="withdrawal_amount_nonnegative",
            ),
        ),
    ]
