# Generated by Django 6.1.1 on 2026-09-13 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='claimed', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='promotions.promotion')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('promotion', 'worker'), name='unique_promotion_worker')],
            },
        ),
    ]
