# Generated by Django 6.1.1 on 2026-09-22 17:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
