# Generated by Django 6.1.1 on 2026-09-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_promotion_reward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'permissions': [('approve_promotion_claim', 'Can approve promotion claims'), ('reject_promotion_claim', 'Can reject promotion claims')]},
        ),
    ]
