# Generated by Django 6.1.1
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [("promotions", "0005_alter_promotion_options"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AlterField(model_name="promotionclaim", name="promotion", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="promotions.promotion")),
        migrations.AlterField(model_name="promotionclaim", name="worker", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="promotion_claims", to=settings.AUTH_USER_MODEL)),
    ]
