# Generated by Django 6.1.1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0006_protect_claim_history"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(reward__gte=0),
                name="promotion_reward_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(budget__gte=0),
                name="promotion_budget_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(completed_workers__lte=models.F("max_workers")),
                name="promotion_completed_lte_max_workers",
            ),
        ),
    ]
