# Generated by Django 6.1.1 on 2026-09-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('approve_task_submission', 'Can approve task submissions'), ('reject_task_submission', 'Can reject task submissions')]},
        ),
    ]
