# Generated by Django 6.1.1 on 2026-09-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'permissions': [('approve_task_submission', 'Can approve task submissions'), ('reject_task_submission', 'Can reject task submissions')]},
        ),
    ]
