# Generated by Django 6.1.1
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [("tasks", "0003_alter_task_options"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AlterField(model_name="taskclaim", name="task", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="tasks.task")),
        migrations.AlterField(model_name="taskclaim", name="worker", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="task_claims", to=settings.AUTH_USER_MODEL)),
    ]
