# Generated by Django 6.1.1
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_protect_claim_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskclaim",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="tasks.task",
            ),
        ),
    ]
