# Generated by Django 6.1.1
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_taskclaim_task"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(reward__gte=0),
                name="task_reward_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(completed_workers__lte=models.F("max_workers")),
                name="task_completed_lte_max_workers",
            ),
        ),
    ]
