# Generated by Django 6.1.1
from decimal import Decimal

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_financial_capacity_invariants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="reward",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
